{
 "title": "Fraud Detection Copy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fraud_request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Legitimate Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "legit_detected_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fraud Detected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fraud_detected_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions vs Fraud over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "increase(fraud_request_total[1m])",
     "legendFormat": "{{All Transactions}}"
    },
    {
     "expr": "increase(fraud_detected_total[1m])",
     "legendFormat": "{{Fraud Detected}}"
    }
   ]
  },
  {
   "title": "Avg Fraud Probability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fraud_probability_avg", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "% Legit transactions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "legit_detected_total / fraud_request_total * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}